version: '3.8'

services:
  web:
    build: .
    ports:
      - "18001:8000"
    networks:
      - webnet
    env_file:
      - .env

  jaeger:
    image: jaegertracing/all-in-one:1.41
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14268:14268"
    networks:
      - webnet

networks:
  webnet:
